#!/usr/bin/env bash
# Performs directory operations based on the most recently opened finder window
# pwdf can be used to compose various other functions

function pwdf() {
  finder_dir=$(/usr/bin/env osascript <<-EOF
    tell application "Finder"
      try
        set the_path to (folder of the front window as alias)
        on error
          set the_path to ("~/")
      end try

      POSIX path of the_path
    end tell
EOF
  )
  echo $finder_dir
}

function cdf() {
  cd $(pwdf)
  >&2 echo $(pwd)
}

function ef(){
  $EDITOR $(pwdf)
}
